{100}{}{Tu vois un homme débraillé portant une blouse blanche.}
{101}{}{Tu vois Jacob le chimiste.}
{102}{}{Tu vois un homme débraillé avec une blouse blanche tachée et dont les mains sont décolorées par les produits chimiques.}
{103}{JACOB1}{Salut. Je suis, Jacob, le chimiste du Bric-à-Brac du Petit Chimiste. Que puis-je faire pour toi ?}
{104}{JACOB2}{Que veux-tu ?}
{105}{JACOB3}{Rebonjour ! Que puis-je faire pour toi aujourd'hui ?}
{106}{JACOB4}{Content de te revoir. Que puis-je faire pour toi ?}
{107}{}{Da gnaga ! Ouga ouba !}
{108}{}{Des bics et bacs ?}
{109}{}{J'ai du minerai à raffiner, mais je refuse de payer les prix pratiqués à la raffinerie.}
{110}{}{Que peux-tu me dire sur les Collines Brisées ?}
{111}{}{J'ai des produits chimiques à mélanger.}
{112}{}{On m'a dit de te contacter à propos d'une certaine affaire en rapport avec les mutants.}
{113}{}{Salut.}
{114}{JACOB5}{[Une expression de dégoût passe sur son visage.] Sors d'ici. Je n'ai pas de temps à perdre.}
{115}{}{[Terminé]}
{116}{JACOB7}{Un Bric-à-Brac. C'est un Bric-à-Brac. Ecoute, tu veux quelque chose ?}
{117}{JACOB6}{Encore toi ? Tu veux quelque chose ?}
{118}{}{'ui !}
{119}{}{Gnnn heu.}
{120}{JACOB8}{D'accord. Voyons voir ce que tu veux.}
{121}{}{[Plus]}
{122}{JACOB10}{Alors va-t'en.}
{123}{}{[Terminé]}
{124}{JACOB11}{Voilà. C'est fait. Merci du conseil. Maintenant, va-t'en s'il te plaît.}
{125}{}{D'OOkK !}
{148}{JACOB12}{Pourquoi ne commences-tu pas par me dire ce que tu penses des mutants ?}
{149}{}{Je les déteste.}
{150}{}{Je n'ai pas les idées claires à leur sujet.}
{151}{}{Je les aime bien !}
{152}{}{Dans ce cas, je vais te raconter la vraie histoire.}
{153}{JACOB14}{Un humain nommé Jacob (c'est de lui dont je tiens mon nom) a fondé cet endroit. Le mutant Marcus est arrivé et a placé tout le monde sous son joug.}
{154}{}{Ca suffit. Tu n'as pas tout ton esprit. Au revoir.}
{155}{}{Quoi d'autre ?}
{156}{JACOB15}{Peut-être que si je te raconte la véritable histoire, tu changeras d'avis.}
{157}{}{Ok. Raconte.}
{158}{}{Non, ça ne m'intéresse pas vraiment.}
{159}{JACOB16}{Eh bien, c'est tout simplement génial de vivre ici. Cette ville a tout ce qu'on peut souhaiter... un shérif mutant, une mine d'uranium, un hôpital, un magasin... tout est là. Autre chose ?}
{160}{}{Oui.}
{161}{}{Non.}
{162}{JACOB17}{Formidable. Au revoir.}
{163}{}{Salut.}
{164}{JACOB18}{Il est au pouvoir ici depuis que le Maître a été détruit. Il réprime tous ceux qui ne sont pas d'accord avec lui... ou il les fait tout simplement disparaître. On dirait que la ville est civilisée, mais en fait c'est le théâtre de tueries perpétrées par des mutants assoiffés de sang. Trop d'amis à moi ont disparu pour s'être élevés contre lui.}
{165}{}{Continue.}
{166}{}{Ca suffit. Tu n'as pas tout ton esprit. Au revoir.}
{167}{JACOB19}{On prétend tous que c'est une ville civilisée, que tout va pour le mieux dans le meilleur des mondes... mais nous vivons dans la terreur des mutants. Chaque jour, il y a de moins en moins d'humains.}
{168}{}{Tous les mutants que j'ai vus semblent vieux et décrépis.}
{169}{}{Pourquoi ne pas vous rebeller ?}
{170}{JACOB20}{C'est parce qu'ils essaient de te berner.}
{171}{}{Pourquoi ne pas vous rebeller contre eux alors ?}
{172}{}{Me berner ? Je vois. Bon, je dois y aller. Ca m'a fait plaisir de te parler.}
{173}{JACOB21}{C'est ce qu'on fait. Avec des amis, nous avons prévu de débarrasser cette ville des mutants, mais il faut d'abord qu'on fasse sortir des amis de prison. Es-tu des nôtres ?}
{174}{}{Non.}
{175}{}{Non. Et je vais même te dénoncer. Tu es fou.}
{176}{}{Bien sûr !}
{177}{JACOB22}{Pas de regrets ? Tu sais, c'est une occasion de libérer l'humanité de ces salauds de mutants vicieux.}
{178}{}{Toujours pas d'accord.}
{179}{}{Oh, d'accord. Tu as réussi à me convaincre.}
{180}{JACOB23}{Comme tu le sens. Je te laisse continuer ton chemin. Mais c'est dommage. T'as l'air balèze.}
{181}{}{Ouais. Salut.}
{182}{JACOB24}{Vraiment, hé ? Je te crois pas, espèce de traître.}
{183}{}{Quoi ?}
{184}{JACOB25}{J'ai du boulot pour toi. Nos amis Manson et Franc sont en prison. Je veux que tu les fasses sortir. Sans faire de grabuge, si possible. Je ne veux pas que toute la ville te recherche.}
{185}{}{Et si je tue quelqu'un ?}
{186}{}{Je comprends. J'ai d'autres questions.}
{187}{}{Laisse tomber. J'abandonne.}
{188}{}{Bien reçu. A plus.}
{189}{JACOB26}{Pas de problème. Tous des mutants de toute façon. Mais fais ça discrètement, je t'en prie.}
{190}{}{Je comprends. J'ai d'autres questions.}
{191}{}{Bien reçu. A plus.}
{192}{JACOB27}{D'autres questions ?}
{193}{}{J'ai du minerai à raffiner, mais je refuse de payer les prix pratiqués à la raffinerie.}
{194}{}{Que peux-tu me dire sur les Collines Brisées ?}
{195}{}{J'ai des produits chimiques à mélanger.}
{196}{}{Rien. Salut.}
{222}{}{Tu trahis les tiens, sale philo-mutant. Comment as-tu pu faire ça à Chad ? Je me fous de ce que tu as fait pour nous. Tu es la honte de l'humanité !}
{223}{}{Salut.}
{224}{JACOB28}{Bravo pour la prison !}
{225}{JACOB9}{Merci.}
{226}{JACOB29}{Tu pouvais vraiment pas éviter de tuer tout le monde ? Ils vont tous être inquiets maintenant. Enfin, tant pis.}
{227}{}{Pardon.}
{228}{JACOB30}{Tu les as tirés de là. C'est le plus important. Evidemment, tout le monde en ville sait maintenant qu'il y a un lien entre toi et Manson et Franc. Mais bon.}
{229}{}{Pardon.}
{230}{JACOB31}{Je crois qu'on peut te faire confiance. Maintenant que t'es bel et bien avec nous, ça te plairait de faire un autre petit boulot ?}
{231}{JACOB32}{Que puis-je faire d'autre pour toi ?}
{232}{}{Un autre boulot ? Comme quoi ?}
{233}{}{J'ai du minerai à raffiner.}
{234}{}{Pas encore. J'ai besoin de produits chimiques.}
{235}{}{Pas tout de suite, merci. Salut.}
{258}{JACOB33}{C'est comme ça. On déteste les mutants. On veut les tuer. Le meilleur moyen de s'en débarrasser c'est de faire sauter la mine quand ils sont dedans. On veut que tu places la charge d'explosifs.}
{259}{}{Je vais le faire !}
{260}{}{Je ne peux pas faire ça.}
{261}{}{Génial ! Tiens. Prends ce détonateur. Place-le sur le purificateur d'air et barre-toi vite. On fera en sorte que les mutants de la ville soient dans la mine.}
{262}{JACOB34}{Tiens-moi au courant quand tu peux y aller.}
{263}{}{C'est bon.}
{264}{}{Je ne peux pas le faire.}
{265}{JACOB36}{Pourquoi pas ? T'as la trouille ou quoi ? Tu le feras pas ? Sûr de sûr ?}
{266}{}{Oui.}
{267}{}{Non, je vais le faire.}
{268}{JACOB37}{J'imagine que je peux comprendre. Tu me comprendras aussi, j'espère, si je te dis de te barrer vite fait. Sale traître !}
{269}{}{[Terminé]}
{270}{JACOB38}{Tu peux commencer à exécuter notre plan ?}
{272}{}{Oui. Allons-y.}
{273}{}{J'ai changé d'avis. Je ne veux pas faire ça.}
{274}{JACOB39}{Bien. J'attendais ce jour. Tu dois juste placer le détonateur sur le purificateur dans la mine et te barrer. Il va y avoir une explosion terrible. On se voit après !}
{275}{}{Tchao ! Mort aux mutants !}
{276}{}{J'ai changé d'avis. Je ne veux pas le faire.}
{277}{}{Fourbe de traître.}
{278}{}{T'as fait du bon travail. Une fois. Dommage que tu te retournes contre nous.}
{279}{JACOB40}{Nous sommes enfin libérés du fléau des mutants ! Merci infiniment pour ton aide. Il y a une petite cache d'armes dans la cave située sous le magasin de Lise. En récompense de ta loyauté, tu peux aller te servir là-bas.}
{280}{}{On quitte la ville. Tu devrais partir aussi.}
{281}{}{Viens me voir au magasin et on parlera.}
{282}{}{Ton minerai est prêt. Voilà.}
{283}{}{Merci !}
{284}{}{Je n'ai pas encore terminé avec le minerai. Laisse-moi du temps.}
{285}{}{J'avais d'autres questions.}
{286}{}{Ok. Au revoir.}
{287}{}{On la fait cette diversion ?}
{288}{}{On essaie encore cette diversion ?}
{289}{}{T'as compris. Tu veux m'aider à faire diversion ?}
{290}{}{Je voudrais acheter... heu... des médicaments.}
{291}{JACOB41}{Rien d'autre ?}
{292}{}{Oui.}
{293}{}{Non merci. Salut.}
{294}{}{Tu te rends maintenant compte de la perfidie des mutants. Si seulement tu l'avais réalisée avant !}
{295}{}{Si tu ne nous aides pas, on ne t'aidera pas non plus.}
{296}{JACOB42}{Dis donc, que fais-tu là à végéter ? Tu as des patriotes à sauver de l'incarcération !}
{297}{}{Oh... C'est vrai.}
{298}{JACOB43}{Je t'ai dit de les faire sortir de prison, pas de les faire tuer ! Mais c'est quoi ton problème ?}
{299}{}{Je regrette... C'est juste...}
{300}{JACOB44}{Juste rien du tout. Que tu l'aies voulu ou non, t'as royalement foutu nos plans en l'air. Maintenant tu vas morfler !}
{301}{JACOB45}{Je regrette, mais... Je viens de perdre mes deux meilleurs amis. Ces saletés de mutants les ont tués en prison.}
{302}{}{Arrggg. Doooommaaage. Salut.}
{303}{}{Heu... Mince alors. C'est triste. Accepte mes condoléances. Salut.}
{304}{}{Oh là là !}
{305}{JACOB46}{Houpela ? T'as dit *Houpela* ? T'as rien à voir avec tout ça, n'est-ce pas ?}
{306}{}{C'était un accident, j'le jure !}
{307}{}{Bien sûr que non ! Saloperies de mutants !}
{308}{JACOB47}{Accident mon cul ! Tu vas me le payer !!}
{309}{JACOB48}{Ouais, bon... Leur tour viendra.}
{310}{JACOB49}{Je t'ai déjà dit tout ce que tu dois savoir sur cet endroit. Alors ! Tu veux quoi ?}
{311}{}{J'ai d'autres questions à te poser.}
{312}{}{Rien. Laisse tomber.}
{313}{JACOB9}{Merci.}
{314}{}{[Continue]}
{315}{JACOB50}{Hé, c'est vraiment sympa d'avoir tiré nos amis d'un mauvais pas. T'as une tête qui me revient bien.}
{316}{JACOB9}{Merci.}

##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{JACOB13}{In that case, I'll give you the real history. A human named Jacob -- I was named after him -- founded this place. Then mutant Marcus came along and forced everyone under his rule. }
{7701}{JACOB35}{Excellent, my friend! Here. Take this explosive switch. Hook it up to the air purifier and get the hell out of there. We've arranged it so that the town's mutants will be in the mine. Just let me know when you're ready to go.}
