{100}{}{Un petit garçon.}
{101}{}{Tu vois Jonny.}
{102}{}{Cheveux blonds, yeux bleus, le gosse américain typique.}
{150}{}{Ouiiin !}
{151}{}{Je veux qu'on me rende mon chien !}
{152}{}{::Pleurs::}
{153}{}{Inconnu !}
{154}{JONNY1}{Laddie ! Tu m'as manquée ! Merci de m'avoir ramené mon chien.}
{155}{JONNY2}{Bonjour, c'est la première fois que je vous vois dans le coin.}
{156}{}{Tu t'appelles Jonny ?}
{157}{}{Comment t'appelles-tu mon garçon ?}
{158}{}{Allez, dis-moi ton nom, petit monstre.}
{159}{}{Eh petit, tu veux un bonbon ?}
{160}{JONNY3}{Rebonjour.}
{166}{}{Ta mère et ton père m'ont demandé de te retrouver.}
{168}{JONNY4}{Avez-vous parlé de mon retour à la maison avec Vegeir ?}
{169}{}{Oui. Il dit qu'il veut que tes parents viennent te chercher.}
{170}{}{Non, pas encore.}
{171}{JONNY5}{Mon père dit que Laddie est venue avec toi pour me chercher. Où est-elle ? Elle me manque.}
{172}{}{Malheureusement Jonny, Laddie est morte pendant que nous te cherchions.}
{173}{}{Rose a dit qu'elle s'occuperait bien de ton chien.}
{174}{JONNY6}{Je m'appelle Jonny, et toi ?}
{175}{}{Je m'appelle }
{176}{}{.}
{177}{}{Peu importe mon nom.}
{178}{JONNY7}{Je m'appelle Jonny et je ne t'aime pas.}
{179}{JONNY8}{[Il te montre du doigt et se met à hurler :] Etranger ! Etranger ! Etranger !}
{180}{}{Très heureux de te rencontrer, }
{181}{}{.}
{182}{}{A un de ces jours, gamin.}
{183}{JONNY10}{C'est dingue ! Je veux rentrer mais Vegeir dit que son peuple ne peut pas voyager longtemps en plein air et qu'ils ne peuvent pas m'emmener... C'est pas que je vous crois pas mais, comment s'appelle mon père ?}
{184}{}{Farrel.}
{185}{}{Cornélius.}
{186}{}{Balthas.}
{187}{}{Davin.}
{188}{}{Joshua.}
{189}{}{Tu ne me fais pas confiance ?}
{190}{JONNY11}{Hmm... Non. Merci d'avoir ramené mon chien, mais je dois partir maintenant. Au revoir.}
{191}{JONNY12}{C'était chouette de vous rencontrer, mais 'faut que je m'en aille maintenant.}
{192}{JONNY13}{Ouais ! Youpi ! Je vais rentrer chez moi. Demandez à Vegeir s'il veut bien que vous me rameniez chez moi. Il a été très gentil avec moi. Je ne veux pas partir sans sa permission. Dépêchez-vous, j'ai vraiment envie de rentrer !}
{193}{JONNY14}{Ok Monsieur, je vous crois. Demandez à Vegeir s'il veut bien que vous me rameniez chez moi. Il a été très gentil avec moi. Je ne veux pas partir sans sa permission.}
{194}{JONNY15}{Ok Madame, je vous crois. Demandez à Vegeir s'il veut bien que vous me rameniez chez moi. Il a été très gentil avec moi. Je ne veux pas partir sans sa permission.}
{195}{JONNY16}{Non. Je vais jouer avec mes amis. Salut.}
{196}{JONNY17}{J'ai pas le droit de parler aux étrangers.}
{197}{JONNY18}{Oui, c'est ça. Comment le savez-vous ? C'est Laddie qui a dû vous le dire, elle est tellement intelligente.}
{199}{}{Tu vas venir avec moi gamin, il y a une récompense pour te ramener.}
{200}{}{Oui, je crois qu'il vaut mieux. C'est pas que je vous fais pas confiance, mais je suis sûr que Vegeir veut juste s'assurer que je rentrerai en toute sécurité. Merci de votre aide.}
{201}{JONNY19}{Dépêchez-vous, je veux rentrer à la maison !}
{202}{JONNY20}{Non ! Je ne vous crois pas ! Rendez-moi mon chien ! [Ouiiin !]}
{203}{JONNY21}{Oh non ! Il paraît que Rose met de la viande de chien dans ses plats ! Laddie est probablement un hamburger à l'heure qu'il est !}
{300}{}{Laddie !!!}
{400}{}{Merci de m'avoir sauvé, monsieur.}
{401}{}{C'est bon d'être à la maison !}
{402}{}{Ouah...}
{403}{}{Tu sais, j'ai plus peur du noir maintenant !}
{404}{}{Merci de m'avoir sauvé, madame.}

##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{JONNY9}{Very nice to meet you Stranger.}
