{100}{}{You see a small boy.}
{101}{}{You see Jonny.}
{102}{}{Blonde hair, blue eyes; your typical all-American looking kid.}

{150}{}{Waaaaa!}
{151}{}{I want my dog back!}
{152}{}{Whimper... }
{153}{}{Stranger!}
{154}{JONNY1}{Laddie! I've missed you, boy. Thank you for bringing my dog back to me.}
{155}{JONNY2}{Hello, I haven't seen you around here before.}
{156}{}{Is your name Jonny?}
{157}{}{What's your name, little boy?}
{158}{}{Tell me your name, you little monster.}
{159}{}{Would you like some candy, little kid?}
{160}{JONNY3}{Hello again.}
{166}{}{Your mother and father have sent me to find you.}
{168}{JONNY4}{Have you talked to Vegeir about me going home?}
{169}{}{Yes. He says he wants your parents to come down and get you.}
{170}{}{No, not yet.}
{171}{JONNY5}{My dad said Laddie went with you to look for me. Where is he? I miss him.}
{172}{}{I'm sorry Jonny. Laddie died while we were searching for you.}
{173}{}{Rose said she would look after your dog.}
{174}{JONNY6}{My name is Jonny. What's yours?}
{175}{}{My name is }
{176}{}{.}
{177}{}{My name's not important.}
{178}{JONNY7}{My name's Jonny, and I don't like you.}
{179}{JONNY8}{[He points to you and starts screaming.] Stranger! Stranger! Stranger!}
{180}{}{Very nice to meet you }
{181}{}{.}
{182}{}{See you around, kid.}
{183}{JONNY10}{That's swell! I wanted to go home, but Vegeir says his people can't travel that far above
 ground and wouldn't take me... Not that I doubt you, but what's my father's name?}
{184}{}{Farrel.}
{185}{}{Cornelius.}
{186}{}{Balthas.}
{187}{}{Davin.}
{188}{}{Joshua.}
{189}{}{Don't you trust me, Jonny?}
{190}{JONNY11}{Hmm... no. Thank you for bringing my dog back to me, but I have to go now. Bye.}
{191}{JONNY12}{It was sure nice meeting you, but I have to go now. Bye.}
{192}{JONNY13}{That's right! Yipee! I'm going home. Ask Vegeir if it's all right for you to take me home. He's
 been so nice to me, I don't want to leave until he says it's all right. Please hurry; I'm homesick.}
{193}{JONNY14}{Okay mister, I believe you. Ask Vegeir it's all right for you to take me home. He's been so nice
 to me, I don't want to leave until he says it's all right.}
{194}{JONNY15}{Okay miss, I believe you. Ask Vegeir it's all right for you to take me home. He's been so nice
 to me, I don't want to leave until he says it's all right.}
{195}{JONNY16}{No. I'm going to go play with my friends now. Bye.}
{196}{JONNY17}{I'm not supposed to talk to strangers. Bye.}
{197}{JONNY18}{Yes it is! How did you know? Laddie must have told you. She's such a smart dog.}
{199}{}{You're coming with me, kid. There's a reward for bringing you back.}
{200}{}{Yes, I think that's best. Although I trust you, I'm sure Vegeir just wants to make sure I get
 home safely. Thank you for your help.}
{201}{JONNY19}{Please hurry. I want to go home.}
{202}{JONNY20}{No! I don't believe you! Give me back my dog! [Waaaaa!]}
{203}{JONNY21}{Oh no! Don't you know Rose uses dog in her dishes!? Laddie is probably a burger by now.}

{300}{}{Laddie!!!}

{400}{}{Thanks for saving me, mister.}
{401}{}{It's nice to be home!}
{402}{}{Wahoo...}
{403}{}{You know, I'm not afraid of the dark anymore!}
{404}{}{Thanks for saving me, lady.}

##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{JONNY9}{Very nice to meet you Stranger.}
